# Generated by Django 5.2.1 on 2025-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'company'), ('job seeker', 'JobSeeker')], max_length=50),
        ),
    ]
