# Generated by Django 5.2.1 on 2025-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_notification_related_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
